os:
- linux
- osx
language: generic
sudo: required
dist: trusty
osx_image: xcode10
install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)";
    swiftenv install 5.0;
    swiftenv global 5.0;
    export LD_LIBRARY_PATH=$HOME/.swiftenv/versions/5.0/usr/lib/swift/linux:$LD_LIBRARY_PATH;
  fi
- swift --version
script:
- make test
- ./dogFooding.sh -diagnostics-only
after_success:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./runXcodeTest.sh; bash <(curl -s https://codecov.io/bash); fi
- ./lint.sh
